/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokedex;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author MEDAC
 */
public class Pokedex1 extends javax.swing.JFrame {
    private ConexionBD conexion = new ConexionBD();
    Connection dbConnection =null;
    Statement statement= null;
    Statement statement2 = null;
    ResultSet resultadot=null;
    String pkm;
    
    
    

    /**
     * Creates new form Pokedex1
     */
    public Pokedex1() {
        initComponents();
        Panel_datos.setVisible(false);
        label_desc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_encender = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_ins = new javax.swing.JButton();
        btn_act = new javax.swing.JButton();
        btn_bor = new javax.swing.JButton();
        Panel_datos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_numero = new javax.swing.JLabel();
        label_tipo1 = new javax.swing.JLabel();
        label_tipo2 = new javax.swing.JLabel();
        label_generacion = new javax.swing.JLabel();
        label_desc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf2_ins = new javax.swing.JTextField();
        tf1_ins = new javax.swing.JTextField();
        tf5_ins = new javax.swing.JTextField();
        tf3_ins = new javax.swing.JTextField();
        tf4_ins = new javax.swing.JTextField();
        tf6_ins = new javax.swing.JTextField();
        cbx = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Tipo 1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_encender.setBackground(new java.awt.Color(51, 102, 255));
        btn_encender.setForeground(new java.awt.Color(255, 255, 0));
        btn_encender.setText("ENCENDER");
        btn_encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encenderActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        btn_ins.setBackground(new java.awt.Color(51, 102, 255));
        btn_ins.setForeground(new java.awt.Color(255, 255, 0));
        btn_ins.setText("INSERTAR");
        btn_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insActionPerformed(evt);
            }
        });

        btn_act.setBackground(new java.awt.Color(51, 102, 255));
        btn_act.setForeground(new java.awt.Color(255, 255, 0));
        btn_act.setText("ACTUALIZAR");

        btn_bor.setBackground(new java.awt.Color(51, 102, 255));
        btn_bor.setForeground(new java.awt.Color(255, 255, 0));
        btn_bor.setText("BORRAR");

        Panel_datos.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Generación");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Nº");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Tipo 1");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Tipo 2");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Descripción");

        label_nombre.setText("jLabel10");

        label_numero.setText("jLabel11");

        label_tipo1.setText("jLabel12");

        label_tipo2.setText("jLabel13");

        label_generacion.setText("jLabel14");

        javax.swing.GroupLayout Panel_datosLayout = new javax.swing.GroupLayout(Panel_datos);
        Panel_datos.setLayout(Panel_datosLayout);
        Panel_datosLayout.setHorizontalGroup(
            Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_datosLayout.createSequentialGroup()
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_numero)
                            .addComponent(label_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(label_tipo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(label_tipo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(label_generacion)))
                    .addGroup(Panel_datosLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel9)))
                .addGap(28, 28, 28))
        );
        Panel_datosLayout.setVerticalGroup(
            Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_datosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(label_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_datosLayout.createSequentialGroup()
                        .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(label_numero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(label_generacion)))
                    .addGroup(Panel_datosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(label_tipo1)
                        .addGap(12, 12, 12)
                        .addComponent(label_tipo2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9))
        );

        label_desc.setBackground(new java.awt.Color(0, 0, 0));
        label_desc.setForeground(new java.awt.Color(0, 0, 0));
        label_desc.setText("A Sceptile le crecen en la espalda unas semillas llenas de nutrientes que sirven para revitalizar los árboles. De hecho, se dedica a cuidarlos con mimo para que crezcan bien");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("POKÉDEX");

        cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pokemon", "Entrenador", "Generacion", "Movimiento", "Profesor", "Gimnasio", "Lider", "Objeto" }));
        cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Tabla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_encender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_desc)
                                    .addComponent(btn_bor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_act))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf1_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf2_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf3_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf4_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf5_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf6_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(btn_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jLabel7)
                    .addContainerGap(602, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_encender, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(label_desc)
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf5_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf3_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf4_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf6_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ins)
                    .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btn_act)
                .addGap(18, 18, 18)
                .addComponent(btn_bor)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel7)
                    .addContainerGap(717, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encenderActionPerformed
        dbConnection=conexion.conexion_correcta();
        jPanel2.setBackground(Color.green);
    }//GEN-LAST:event_btn_encenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        pkm = jTextField1.getText();
        try {
            statement = dbConnection.createStatement();
            resultadot = statement.executeQuery("select * from pokemon where nombre = '"+pkm+"'");
            
            while(resultadot.next()) {
                label_nombre.setText(resultadot.getString("nombre"));
                label_numero.setText(resultadot.getString("numero"));
                label_tipo1.setText(resultadot.getString("tipo1"));
                if(resultadot.getString("tipo2") == null)
                {
                    label_tipo2.setText("---");
                }else
                {
                    label_tipo2.setText(resultadot.getString("tipo2"));
                }
                label_generacion.setText(resultadot.getString("generacion_numero"));
                label_desc.setText(resultadot.getString("descripcion"));
                Panel_datos.setVisible(true);
                label_desc.setVisible(true);
                
                /* Consola
                System.out.println(resultadot.getInt("numero"));
                System.out.println(resultadot.getString("nombre"));
                System.out.println(resultadot.getString("tipo1"));
                System.out.println(resultadot.getString("tipo2"));
                System.out.println(resultadot.getString("descripcion"));
                System.out.println(resultadot.getInt("generacion_numero"));*/
            }

        } catch (SQLException e1) {

            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insActionPerformed
        try {
            
            String cbxItem = cbx.getSelectedItem().toString();
            int tablae =-1
                    ;
            if(cbxItem.contains("Pokemon"))
            {
               tablae = 0;
            }else if(cbxItem.contains("Entrenador")){
            tablae = 1;
            }
            else if(cbxItem.contains("Generacion")){
            tablae = 2;
            }
            else if(cbxItem.contains("Movimiento")){
            tablae = 3;
            }
            else if(cbxItem.contains("Profesor")){
            tablae = 4;
            }
            else if(cbxItem.contains("Gimnasio")){
            tablae = 6;
            }
            else if(cbxItem.contains("Lider")){
            tablae = 7;
            }
            else if(cbxItem.contains("Objeto")){
            tablae = 8;
            }
            
            switch (tablae) {
                case 0:
            String at1 = tf1_ins.getText();
            String at2 = tf2_ins.getText();
            String at3 = tf3_ins.getText();
            String at4 = tf4_ins.getText();
            String at5 = tf5_ins.getText();
            String at6 = tf6_ins.getText();
            statement = dbConnection.createStatement();
            int resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6);
                break;
                case 1:
             at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText(); 
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Genero,Rol) values('"+at1+"',"+at2+","+"'"+at3+"'");
                break; 
                case 2:
             at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText();
             at4 = tf4_ins.getText();
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6);
                break; 
                case 3:
             at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText();
             at4 = tf4_ins.getText();
             at5 = tf5_ins.getText();
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6); 
                break; 
                case 4:
             at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText();
             at4 = tf4_ins.getText();
             at5 = tf5_ins.getText();
             at6 = tf6_ins.getText();
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6); 
                break; 
                case 6:
             at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText();
             at4 = tf4_ins.getText();
             at5 = tf5_ins.getText();
             at6 = tf6_ins.getText();
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6);
                break; 
                case 7:
                    at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText();
             at4 = tf4_ins.getText();
             at5 = tf5_ins.getText();
             at6 = tf6_ins.getText();
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6); 
                break; 
                case 8:
             at1 = tf1_ins.getText();
             at2 = tf2_ins.getText();
             at3 = tf3_ins.getText();
             at4 = tf4_ins.getText();
             at5 = tf5_ins.getText();
             at6 = tf6_ins.getText();
            statement = dbConnection.createStatement();
             resultado = statement.executeUpdate("insert into Pokemon(Nombre,Numero,Tipo1,Tipo2,Descripcion,Objeto_Nombre,Generacion_Numero) values('"+at1+"',"+at2+",'"+at3+"','"+at4+"','"+at5+"',null,"+at6);
                break; 
            }
            
           
        } catch (SQLException e1) {

            e1.printStackTrace();
        }
    }//GEN-LAST:event_btn_insActionPerformed

    private void cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxActionPerformed
    

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("iconoP.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pokedex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pokedex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pokedex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pokedex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pokedex1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_datos;
    private javax.swing.JButton btn_act;
    private javax.swing.JButton btn_bor;
    private javax.swing.JButton btn_encender;
    private javax.swing.JButton btn_ins;
    private javax.swing.JComboBox<String> cbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_desc;
    private javax.swing.JLabel label_generacion;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_numero;
    private javax.swing.JLabel label_tipo1;
    private javax.swing.JLabel label_tipo2;
    private javax.swing.JTextField tf1_ins;
    private javax.swing.JTextField tf2_ins;
    private javax.swing.JTextField tf3_ins;
    private javax.swing.JTextField tf4_ins;
    private javax.swing.JTextField tf5_ins;
    private javax.swing.JTextField tf6_ins;
    // End of variables declaration//GEN-END:variables
}
